Make m5 the default instance class
aptible/terraform-provider-aptible pull request #103
Opened 2023-08-28 22:01 UTC by aaw

2023-10-02 13:35 UTC, aaw commented
https://app.shortcut.com/aptible/story/17597/support-m5-as-default

2023-10-03 14:26 UTC, aaw commented
@joshraker friendly ping for a review

2023-10-03 14:37 UTC, joshraker requested changes
Just one oddity in the `go.sum`. If you're up for a challenge you could update the profile validation to raise a warning, rather than an error so that the next time we add a profile users can use it without having to update their client right away.

2023-10-03 20:07 UTC, aaw commented on go.sum
>  github.com/aptible/go-deploy v0.5.0/go.mod h1:h0Zt8I+pV3aqvPo+rA1hIeQjT/13RzFPYuTmg4+SyPQ=
Thanks! `go mod tidy` cleaned it up

2023-10-03 20:09 UTC, aaw commented
> Just one oddity in the `go.sum`. If you're up for a challenge you could update the profile validation to raise a warning, rather than an error so that the next time we add a profile users can use it without having to update their client right away.

Turns out the validations for instance profile are [already warnings](https://github.com/aptible/terraform-provider-aptible/blob/master/aptible/validation.go#L79). I tested an example with a bogus instance profile anyway and saw `terraform plan` only give me a warning.

2023-10-03 20:26 UTC, joshraker approved these changes

2023-10-04 13:30 UTC, merged